name: CI

on: [push, pull_request]

jobs:
  job_build:
    name: Compilation
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          make && mv bin/ bitcoin-bin/
          make clean
          make COIN=qtum_stake_testnet && mv bin/ bitcoin-testnet-bin/

      - name: Upload Bitcoin app binary
        uses: actions/upload-artifact@v2
        with:
          name: bitcoin-app
          path: bitcoin-bin

      - name: Upload Bitcoin Testnet app binary
        uses: actions/upload-artifact@v2
        with:
          name: bitcoin-testnet-app
          path: bitcoin-testnet-bin
